<?php

declare(strict_types=1);

/*
 * This file is part of eelly package.
 *
 * (c) eelly.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Shadon\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class ConsumeCommand.
 *
 * @author hehui<runphp@qq.com>
 */
class ConsumeCommand extends Command
{
    /**
     * @var string
     */
    private $moduleName;

    public function __construct(string $module)
    {
        parent::__construct($module.':consume');
        $this->setDescription('consumer command line');
        $this->moduleName = $module;
    }

    /**
     * @return string
     */
    public function getModuleName(): string
    {
        return $this->moduleName;
    }

    protected function execute(InputInterface $input, OutputInterface $output): void
    {
        // parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
